# Archivo: /etc/ssh/sshd_config.d/01-seguridad.conf
# Endurecimiento del servicio OpenSSH

# Deshabilitar inicio de sesión como root por contraseña (solo permitir llaves SSH)
PermitRootLogin prohibit-password

# Deshabilitar autenticación por contraseñas una vez verificadas las llaves
# PasswordAuthentication no

# Limitar acceso exclusivamente a usuarios autorizados
AllowUsers renich admin

# Deshabilitar contraseñas vacías
PermitEmptyPasswords no

# Deshabilitar reenvío X11 si no es necesario
X11Forwarding no
